#! /usr/bin/fish

source $HOME/.config/lemonbar/colors.fish

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8
bspc config normal_border_color  $BACKGROUND
bspc config focused_border_color $BRIGHT_BLACK

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true



feh --bg-fill $HOME/wallpapers/zentree.png &

$HOME/.config/lemonbar/lemonbar.fish | 
lemonbar -p -g x24 -B$BACKGROUND -F$FOREGROUND -o 0 -f "Iosevka:size=11" -o -2 -f "Font Awesome 5 Free:size=11" |
sh
